In [1]:
import numpy as np
import pickle
import json
import pandas as pd

In [2]:
# Scaler
X_scaler = pickle.load(open('../X_scaler.pkl', 'rb'))
y_scaler = pickle.load(open('../y_scaler.pkl', 'rb'))
model = pickle.load(open("../nn_model.pkl", 'rb'))

In [5]:
list = [1,2020,155,1,1,1]
list_arr = np.array(list).reshape(-1,1)
list_scaled = X_scaler.fit_transform(list_arr)
list_scaled

array([[-0.48737984],
       [ 2.22965623],
       [-0.28013687],
       [-0.48737984],
       [-0.48737984],
       [-0.48737984]])

In [12]:
backshape = list_scaled.reshape(1,-1)
pred = model.predict([backshape])
preds = y_scaler.inverse_transform(pred)
preds

1/1 [==============================] - 0s 19ms/step


array([[25038638.]], dtype=float32)

In [14]:
loaded_model = pickle.load(open("../nn_model.pkl", "rb"))

# Print model summary
print(loaded_model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 192)               1344      
                                                                 
 dropout_3 (Dropout)         (None, 192)               0         
                                                                 
 dense_5 (Dense)             (None, 160)               30880     
                                                                 
 dropout_4 (Dropout)         (None, 160)               0         
                                                                 
 dense_6 (Dense)             (None, 32)                5152      
                                                                 
 dropout_5 (Dropout)         (None, 32)                0         
                                                                 
 dense_7 (Dense)             (None, 1)                

In [24]:
#reshaped_array = np.array(list).reshape(-1,1)
loaded_model.predict([list])

1/1 [==============================] - 1s 1s/step


array([[624.048]], dtype=float32)