In [1]:
import numpy as np
import pickle
import json
import pandas as pd

In [2]:
# Scaler
X_scaler = pickle.load(open('../X_scaler.pkl', 'rb'))
y_scaler = pickle.load(open('../y_scaler.pkl', 'rb'))
model = pickle.load(open("../nn_model.pkl", 'rb'))

In [3]:
list = [1,2020,155,1,1]
list_arr = np.array(list).reshape(-1,1)
list_scaled = X_scaler.fit_transform(list_arr)
list_scaled

array([[-0.54705057],
       [ 1.99435555],
       [-0.35320384],
       [-0.54705057],
       [-0.54705057]])

In [4]:
backshape = list_scaled.reshape(1,-1)
pred = model.predict([backshape])
preds = y_scaler.inverse_transform(pred)
preds

1/1 [==============================] - 0s 113ms/step


array([[43072824.]], dtype=float32)

In [5]:
loaded_model = pickle.load(open("../nn_model.pkl", "rb"))

# Print model summary
print(loaded_model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 256)               1536      
                                                                 
 dense_5 (Dense)             (None, 160)               41120     
                                                                 
 dense_6 (Dense)             (None, 256)               41216     
                                                                 
 dropout_1 (Dropout)         (None, 256)               0         
                                                                 
 dense_7 (Dense)             (None, 1)                 257       
                                                                 
Total params: 84129 (328.63 KB)
Trainable params: 84129 (328.63 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [6]:
#reshaped_array = np.array(list).reshape(-1,1)
loaded_model.predict([list])

1/1 [==============================] - 0s 105ms/step


array([[1754.8405]], dtype=float32)

In [8]:
list[2]

155